services:
  og_sm.config_factory_override:
    class: Drupal\og_sm_config\Config\SiteConfigFactoryOverride
    arguments: ['@og_sm.config.storage', '@config.typed']
    tags:
      - { name: config.factory.override, priority: -150 }
      - { name: event_subscriber }
  og_sm.config.storage:
    class: Drupal\Core\Config\CachedStorage
    arguments: ['@og_sm.config.storage.active', '@cache.config']
  og_sm.config.storage.active:
    class: Drupal\Core\Config\DatabaseStorage
    arguments: ['@database', 'og_sm_config']
    public: false
    tags:
      - { name: backend_overridable }
